"""Add am_pm field to ReportDeadline

Revision ID: 4957be5c5938
Revises: dc973a43a5ca
Create Date: 2025-04-26 09:44:41.235990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4957be5c5938'
down_revision = 'dc973a43a5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_deadlines', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hour',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('am_pm',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('reminder_hours_before',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_deadlines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('reminder_hours_before',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('am_pm',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hour',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('day_of_week',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
