"""Add am_pm column to report_deadlines

Revision ID: 89ff084341d6
Revises: d38a4dece902
Create Date: 2025-04-26 00:45:43.456287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ff084341d6'
down_revision = 'd38a4dece902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_deadlines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('am_pm', sa.String(length=2), nullable=True))
        batch_op.alter_column('day_of_week',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hour',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('enable_missing_reports')
        batch_op.drop_column('is_pm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_deadlines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pm', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('enable_missing_reports', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hour',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('day_of_week',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('am_pm')

    # ### end Alembic commands ###
