"""Add is_pm column to report_deadlines

Revision ID: d38a4dece902
Revises: 
Create Date: 2025-04-26 00:33:50.128064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38a4dece902'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_deadlines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pm', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_deadlines', schema=None) as batch_op:
        batch_op.drop_column('is_pm')

    # ### end Alembic commands ###
